# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=250)),
                ('genres', models.TextField(max_length=250)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('movieId', models.ForeignKey(db_column='movieId', on_delete=django.db.models.deletion.CASCADE, to='movie_management.Movie')),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=250)),
                ('password', models.TextField(max_length=256)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='rating',
            name='userId',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='movie_management.User'),
        ),
    ]
