# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
