# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
