# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Movie',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
    ]
