# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0002_auto_20171014_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
