# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0004_remove_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
    ]
