# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0005_remove_movie_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
