# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0006_auto_20171011_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
