# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0007_auto_20171011_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
