# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie_management', '0008_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.TextField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('genres', models.TextField(max_length=150)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
